---
title: "Obtener Ayuda"
output:
  html_document:
    encoding: UTF-8
    theme: spacelab
    highlight: tango
    css:  ~/custom.css
    toc: true
    toc_float: 
      collapsed: false
      smooth_scroll: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, prompt = FALSE, comment = "", collapse = TRUE)
```

Existen cerca de 1000 funciones en la instalación base de R, y en cada actualización
se crean de nuevas. Esto resulta una gran cantidad de material que memorizar y aprender.
Afortunadamente, cada función en R proporciona su propia página de ayuda.


## Páginas de Ayuda

Las páginas de ayuda contienen información de lo que hacen las funciones. Estas
páginas también sirven como documentación para el código.

Podemos acceder a la página de ayuda de una función escribiendo el símbolo __`?`__ 
seguido del nombre de la función.

<div class="alert alert-success" role="alert">
<span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
<span class="sr-only">Exercise:</span>
**Ejercicio:**
Introduce en la consola las siguientes instrucciones e inspecciona las páginas que
aparecerán en la __Pestaña de Ayuda__ situada en la esquina inferior derecha de RStudio:

`?sqrt` </br>
`?log10` </br>
`?sample` </br>
</div>

<div class="alert alert-danger" role="alert">
<span class="glyphicon glyphicon-alert" aria-hidden="true"></span>
<span class="sr-only">Alert:</span>
__Recuerda__ que para acceder a una función de un paquete, R no será capaz de 
encontrar su página de ayuda, a menos que lo hayamos cargado previamente en nuestra
sesión como hemos visto en tareas anteriores.
</div>

## Partes de las Páginas de Ayuda
</br>
Cada página de ayuda está dividida en secciones:

**- _Description_**</br>
  Una breve descripción de lo que hace la función.

**- _Usage_** </br>
  Un ejemplo de como podemos utilizar la función. Cada argumento aparecerá en el
  orden en que R espera que nosotros los proporcionemos (si no usamos los nombres
  de los argumentos).  
  
**- _Arguments_** </br> 
  Una lista de cada argumento que acepta la función, que tipo de información espera
  que proporcionemos y que hará la función con esta información.
  
**- _Value_**</br>
  Una descripción del resultado de la función.
  
**- _See Also_**</br>
  Una lista con funciones R relacionadas.
  
**- _Examples_**</br>
  Código de ejemplo del uso de la función. 
  
</br> 

Si nos encontramos ante la situación de que queremos consultar la página de ayuda
de una función, pero hemos olvidado su nombre, podemos realizar una búsqueda por
palabras clave. Esto podemos hacerlo con la ayuda de dos __`??`__ seguido de la 
palabra clave y presionando la tecla <span class="label label-default">Tab</span>. R abrirá una lista con páginas de ayuda que coincidan con la palabra
clave.
</br></br>  

<div class="alert alert-success" role="alert">
<span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
<span class="sr-only">Exercise:</span>
**Ejercicio:**
Introduce en la consola la siguiente instrucción y accede a la página de ayuda 
de la función `log10()`:

`??log` 
</div>

</br></br> 

<div class="alert alert-success" role="alert">
<span class="glyphicon glyphicon-education" aria-hidden="true"></span>
<span class="sr-only">Instructions:</span>
**Problema:**

Consulta la documentación del paquete `ggplot2()`.
</div>



<div class="alert alert-warning" role="alert">
<span class="glyphicon glyphicon-question-sign" aria-hidden="true"></span>
<span class="sr-only">Question:</span>
**Pregunta :**  

¿Para que se utiliza el paquete `ggplot2()`?
</div>

<div class="alert alert-info" role="alert">
<span class="glyphicon glyphicon-tasks" aria-hidden="true"></span>
**Posibles respuestas:** </br></br> 
<p><span class="glyphicon glyphicon-check" aria-hidden="true"></span>  Para manipular strings.</p>
<p><span class="glyphicon glyphicon-check" aria-hidden="true"></span>  Para manipular fechas.</p> 
<p><span class="glyphicon glyphicon-check" aria-hidden="true"></span>  Para la creación de gráficos.</p>
<p><span class="glyphicon glyphicon-check" aria-hidden="true"></span>  Para la manipulación de `dataframes`.</p>
</div>



<p>
<a class="btn btn-info" data-toggle="collapse" href="#hint" aria-expanded="false" aria-controls="collapseExample">
<span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>  Ayuda</a>
</p>
<div class="collapse" id="hint">
<div class="card card-block">
<div class="alert alert-info" role="alert">
- __Recuerda__ que puesto que `ggplot2` no pertenece al _"core"_ de R, para poder acceder a la documentación de un paquete y sus funciones, previamente tenemos que
cargarlo en nuestra sesión R. Si no recuerdas como hacerlo, visualiza de nuevo el 
video o realiza la tarea 11.

</div>
</div>
