---
title: 
output:
  html_document:
    encoding: UTF-8
    theme: spacelab
    highlight: tango
    css:  ~/custom.css
    toc: true
    toc_float: 
      collapsed: false
      smooth_scroll: true
---
# Atajos de Teclado

Además de los atajos de teclado para el historial de comandos, existen una gran
variedad de atajos disponibles. Algunos de los más útiles són los siguientes:

- __Ctrl + 1__ - Desplaza el cursor al Editor
- __Ctrl + 2__ - Desplaza el cursor a la Consola
- __Ctrl + L__ - Limpia la Consola
- __Esc__ - Interrumpe R



## ¿Cómo Limpiar la Consola de R?

Una consola muy llena puede resultar confusa, especialmente cuando trabajemos con
grandes conjuntos de datos. En esta tarea aprenderemos como limpiar la consola de R.


<div class="alert alert-info" role="alert">
<span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
<span class="sr-only">Exercise:</span>
**Ejercicio:**
Introduce en la consola la siguiente instrucción:

```{r eval=FALSE}
datasets::LifeCycleSavings
```
</div>




<div class="alert alert-warning" role="alert">
<span class="glyphicon glyphicon-question-sign" aria-hidden="true"></span>
<span class="sr-only">Question:</span>
**Pregunta:**
¿Qué comando utilizarías para limpiar la consola?

**Posibles respuestas:**
<p><span class="glyphicon glyphicon-check" aria-hidden="true"></span>  Command + R</p>
<p><span class="glyphicon glyphicon-check" aria-hidden="true"></span>  Control + R</p>
<p><span class="glyphicon glyphicon-check" aria-hidden="true"></span>  Command + F</p>
<p><span class="glyphicon glyphicon-check" aria-hidden="true"></span>  Control + L</p>
</div>

<p>
<a class="btn btn-info btn-lg" data-toggle="collapse" href="#hint" aria-expanded="false" aria-controls="collapseExample">
<span class="glyphicon glyphicon-question-sign" aria-hidden="true">     </span> Ayuda</a>
</p>
<div class="collapse" id="hint">
<div class="card card-block">
<div class="alert alert-info" role="alert">
Puedes consultar una lista con los atajos de teclado en RStudio desde: 
__Tools > Keyboard Shortucuts Help__
</div>

<div class="alert alert-info" role="alert">
<span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
<span class="sr-only">Info:</span>
**Recuerda:**
En versiones recientes de RStudio, podemos realizar la misma acción con la ayuda
del bóton de la brocha situada en la esquina superior derecha de la consola.


</div>

